language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - travis_retry composer global self-update
  - travis_retry composer global require fxp/composer-asset-plugin:~1.1.1
  - travis_retry composer global require --dev codeception/codeception:~2.1.0
  - travis_retry composer install --prefer-dist --dev

script:
  - ~/.composer/vendor/bin/codecept build
  - ~/.composer/vendor/bin/codecept run

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      ~/.composer/vendor/bin/codecept run --coverage --coverage-xml --coverage-html
    fi

cache:
  - vendor
  - $HOME/.composer/cache

after_success:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
